import { and, asc, count, eq, isNull } from 'drizzle-orm';

import { normalizeBlob } from '@/data/db/blob';
import { db } from '@/data/db/connection';
import { circleMembers } from '@/data/db/schema';

export type Member = typeof circleMembers.$inferSelect;

/** The two roles a member can hold — see `role` on `circleMembers` in schema.ts. */
export type MemberRole = Member['role'];

/** Named values for `MemberRole`, so call sites never hand-type the raw strings. */
export const MemberRoles: Record<MemberRole, MemberRole> = {
  admin: 'admin',
  member: 'member',
};

function normalizeMember(member: Member): Member {
  return { ...member, picture: normalizeBlob(member.picture) };
}

/**
 * Inserts a new member. `member.memberId` must be self-generated by the
 * joining member (via `generateUUID()`), never computed here — that's
 * what lets every device replay the join event and agree on the same ID
 * with zero coordination.
 *
 * A raw insert, so it throws on an identity already on the roster. The
 * app never calls it: every roster change goes through member-events.ts,
 * which upserts and writes the matching history row. Kept for test
 * fixtures that want a roster without a log behind it.
 */
export async function insertMember(member: Member): Promise<void> {
  await db.insert(circleMembers).values(member);
}

/** Looks up a member by their identity (Ed25519 signing) public key — used to verify a post's signature. */
export async function getMemberByPublicKey(circleId: string, identityPublicKey: string): Promise<Member | null> {
  const rows = await db
    .select()
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.identityPublicKey, identityPublicKey)));
  return rows[0] ? normalizeMember(rows[0]) : null;
}

/** Looks up a member by their compact member ID — resolves a post's key reference. */
export async function getMemberByMemberId(circleId: string, memberId: string): Promise<Member | null> {
  const rows = await db
    .select()
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.memberId, memberId)));
  return rows[0] ? normalizeMember(rows[0]) : null;
}

/** Returns every *current* member of a circle, in join order — this is the roster. Excludes removed members; see `getMemberByPublicKey` for the ever-member view. */
export async function getCircleMembers(circleId: string): Promise<Member[]> {
  const members = await db
    .select()
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), isNull(circleMembers.removedAt)))
    .orderBy(asc(circleMembers.joinedAt));
  return members.map(normalizeMember);
}

export async function updateMemberProfile(
  circleId: string,
  identityPublicKey: string,
  profile: { name: string; picture: Uint8Array | null },
): Promise<void> {
  await db
    .update(circleMembers)
    .set(profile)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.identityPublicKey, identityPublicKey)));
}

/** Just the count of *current* members — the circle list shows "N people" and never needs the rows. */
export async function getCircleMemberCount(circleId: string): Promise<number> {
  const rows = await db
    .select({ count: count() })
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), isNull(circleMembers.removedAt)));
  return rows[0]?.count ?? 0;
}
