import { and, asc, eq } from 'drizzle-orm';

import { normalizeBlob } from '@/data/db/blob';
import { db } from '@/data/db/connection';
import { circleMembers } from '@/data/db/schema';

export type Member = typeof circleMembers.$inferSelect;

/** The two roles a member can hold — see `role` on `circleMembers` in schema.ts. */
export type MemberRole = Member['role'];

/** Named values for `MemberRole`, so call sites never hand-type the raw strings. */
export const MemberRoles: Record<MemberRole, MemberRole> = {
  admin: 'admin',
  member: 'member',
};

function normalizeMember(member: Member): Member {
  return { ...member, picture: normalizeBlob(member.picture) };
}

/**
 * Inserts a new member. `member.memberId` must be self-generated by the
 * joining member (via `generateUUID()`), never computed here — that's
 * what lets every device replay the join event and agree on the same ID
 * with zero coordination.
 */
export async function insertMember(member: Member): Promise<void> {
  await db.insert(circleMembers).values(member);
}

/**
 * Inserts a member only if that identity isn't already on the roster —
 * how the sync engine applies a `member_added` entry, which it may see
 * more than once (a crash between applying an entry and advancing the
 * cursor replays it, and a joiner walking meta from 0 reaches its own
 * self-announced entry). See server/SYNC_DESIGN.md invariant 8.
 */
export async function insertMemberIfAbsent(member: Member): Promise<void> {
  await db.insert(circleMembers).values(member).onConflictDoNothing();
}

/** Looks up a member by their identity (Ed25519 signing) public key — used to verify a post's signature. */
export async function getMemberByPublicKey(circleId: string, identityPublicKey: string): Promise<Member | null> {
  const rows = await db
    .select()
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.identityPublicKey, identityPublicKey)));
  return rows[0] ? normalizeMember(rows[0]) : null;
}

/** Looks up a member by their compact member ID — resolves a post's key reference. */
export async function getMemberByMemberId(circleId: string, memberId: string): Promise<Member | null> {
  const rows = await db
    .select()
    .from(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.memberId, memberId)));
  return rows[0] ? normalizeMember(rows[0]) : null;
}

/** Returns every member of a circle, in join order — this is the roster. */
export async function getCircleMembers(circleId: string): Promise<Member[]> {
  const members = await db
    .select()
    .from(circleMembers)
    .where(eq(circleMembers.circleId, circleId))
    .orderBy(asc(circleMembers.joinedAt));
  return members.map(normalizeMember);
}

export async function updateMemberProfile(
  circleId: string,
  identityPublicKey: string,
  profile: { name: string; picture: Uint8Array | null },
): Promise<void> {
  await db
    .update(circleMembers)
    .set(profile)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.identityPublicKey, identityPublicKey)));
}

/** Removes a member from a circle's roster (e.g. after a kick + rotation). */
export async function deleteMember(circleId: string, identityPublicKey: string): Promise<void> {
  await db
    .delete(circleMembers)
    .where(and(eq(circleMembers.circleId, circleId), eq(circleMembers.identityPublicKey, identityPublicKey)));
}
