import { ed25519, x25519 } from '@noble/curves/ed25519.js';
import { bytesToHex, concatBytes, randomBytes } from '@noble/curves/utils.js';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { generateMnemonic, mnemonicToEntropy } from '@scure/bip39';
import { wordlist } from '@scure/bip39/wordlists/english.js';
import { randomUUID } from 'expo-crypto';

/** 128 bits of entropy — the standard tier, same security level as AES-128. */
const SEED_STRENGTH_BITS = 128;

const NONCE_LENGTH = 24;

/**
 * Generates a locally-unique, self-assigned ID (a native RFC4122 UUID v4).
 * One generator, used directly wherever an entity (a circle, a member, a
 * post, ...) needs an ID — no per-entity wrapper function, so adding a new
 * entity type never means adding a new method here that just forwards to
 * this one.
 *
 * For anything a *member* self-assigns to reference themselves (like a
 * post's author, or their own roster entry), it must be generated by that
 * member at the moment they need it, never derived from other members'
 * existing state — that's what lets every device replay the same event
 * and agree on the same ID with zero coordination.
 */
export function generateUUID(): string {
  return randomUUID();
}

/**
 * Generates a fresh 12-word recovery phrase (128 bits of entropy). This is
 * the device's one master seed — persisted locally (never sent anywhere,
 * never shown in the UI today) so future circles can derive their keys
 * from it without asking the user to retype it every time. A manual
 * backup/reveal path (words, QR, or otherwise) is deliberately deferred —
 * not designed yet, nothing to point to for it.
 */
export function generateSeedPhrase(): string {
  return generateMnemonic(wordlist, SEED_STRENGTH_BITS);
}

/**
 * Recovers the raw 16-byte entropy behind a seed phrase — either the one
 * just generated (to persist it) or one a user typed back in during
 * recovery. Throws if the words or checksum aren't a valid BIP39 phrase,
 * which catches most transcription mistakes immediately rather than
 * silently deriving the wrong keys.
 */
export function seedPhraseToEntropy(phrase: string): Uint8Array {
  return mnemonicToEntropy(phrase, wordlist);
}

export type Keypair = {
  publicKey: Uint8Array;
  secretKey: Uint8Array;
};

/**
 * Digits 1-9 plus A-Z minus I/L/O — drops the pairs most often misread
 * (0/O, 1/I/L) when handwritten or read aloud. Exactly 32 symbols so each
 * one maps to 5 bits of a random byte with zero modulo bias (256 / 32 = 8).
 */
const INVITE_CODE_ALPHABET = '123456789ABCDEFGHJKMNPQRSTUVWXYZ';

/**
 * Generates a circle invite code: 12 random characters from a
 * confusion-resistant alphabet, grouped for readability (`XXXX-XXXX-XXXX`).
 * 60 bits of entropy — short enough to read aloud or type by hand, unlike
 * a full UUID, while still being infeasible to guess within an invite's
 * short lifetime. The same string backs both the shareable link and the
 * QR code — there's only ever one secret here, just two presentations of it.
 */
export function generateInviteCode(): string {
  const bytes = randomBytes(12);
  const chars = Array.from(bytes, (byte) => INVITE_CODE_ALPHABET[byte % INVITE_CODE_ALPHABET.length]);
  return [chars.slice(0, 4), chars.slice(4, 8), chars.slice(8, 12)].map((group) => group.join('')).join('-');
}

/**
 * Generates a fresh Ed25519 identity keypair. Call this once per circle —
 * never reuse the same keypair across circles, or your public key becomes
 * a stable pseudonym that links your membership across otherwise-unrelated
 * groups (see the cross-circle correlation discussion).
 */
export function generateIdentity(): Keypair {
  return ed25519.keygen();
}

const CIRCLE_IDENTITY_DOMAIN = new TextEncoder().encode('circle-identity');
const CIRCLE_SEALING_KEY_DOMAIN = new TextEncoder().encode('circle-identity-seal');
const AUTHORITY_KEY_DOMAIN = new TextEncoder().encode('token-authority');
const MANIFEST_KEY_DOMAIN = new TextEncoder().encode('recovery-manifest');

/**
 * Derives a circle's identity keypair (Ed25519, for signing) from the
 * device's master seed — deterministic, so recovering the seed
 * regenerates the same keypair. Domain-separated per circleId, same
 * reasoning as `generateIdentity`'s doc comment.
 */
export function deriveCircleIdentity(masterSeed: Uint8Array, circleId: string): Keypair {
  const seed = hkdf(sha256, masterSeed, undefined, concatBytes(CIRCLE_IDENTITY_DOMAIN, new TextEncoder().encode(circleId)), 32);
  return ed25519.keygen(seed);
}

/**
 * Derives a circle's sealing keypair (X25519), the companion to
 * `deriveCircleIdentity` — used to seal content-key wraps to this member
 * (see `sealToPublicKey`). A different HKDF domain, deliberately: never
 * derive one key type from the other's raw seed.
 */
export function deriveCircleSealingKeypair(masterSeed: Uint8Array, circleId: string): Keypair {
  const seed = hkdf(sha256, masterSeed, undefined, concatBytes(CIRCLE_SEALING_KEY_DOMAIN, new TextEncoder().encode(circleId)), 32);
  return x25519.keygen(seed);
}

/**
 * Derives an admin's authority keypair (Ed25519) — see
 * server/SYNC_DESIGN.md's "token-authority key". Signs control-plane
 * operations (rotating the write token, changing the authority set) that
 * the relay itself verifies, unlike the circle identity above, which only
 * clients verify. Cheap to derive for a non-admin too — it's just never
 * registered with the relay for them.
 */
export function deriveAuthorityKeypair(masterSeed: Uint8Array, circleId: string): Keypair {
  const seed = hkdf(sha256, masterSeed, undefined, concatBytes(AUTHORITY_KEY_DOMAIN, new TextEncoder().encode(circleId)), 32);
  return ed25519.keygen(seed);
}

/**
 * Derives the symmetric key that encrypts the account-recovery manifest
 * (the list of circleIds this account belongs to) before it's sent to the
 * relay — see server/DESIGN.md's "Account recovery" section. The relay
 * only ever stores the resulting ciphertext.
 */
export function deriveManifestKey(masterSeed: Uint8Array): Uint8Array {
  return hkdf(sha256, masterSeed, undefined, MANIFEST_KEY_DOMAIN, 32);
}

/**
 * Generates a fresh, versioned content key: 32 random bytes. Shared by
 * every member holding this version (sealed to each individually — see
 * `sealToPublicKey`); a removed member's exclusion from the *next*
 * version's wraps is what revokes their access — see
 * server/SYNC_DESIGN.md's "Content encryption" section.
 */
export function generateContentKey(): Uint8Array {
  return randomBytes(32);
}

const WRITE_TOKEN_DOMAIN = new TextEncoder().encode('relay-write-token');

/**
 * Derives the write token for one content-key version —
 * `HKDF(contentKey, "relay-write-token")`. Everyone holding this key
 * version computes the identical token; the relay only ever sees its hash
 * (see `hashWriteToken`), never this value or the key it came from. This
 * is what proves "a current member" to the relay without the relay
 * learning who — see server/SYNC_DESIGN.md's "Authorization" section.
 */
export function deriveWriteToken(contentKey: Uint8Array): Uint8Array {
  return hkdf(sha256, contentKey, undefined, WRITE_TOKEN_DOMAIN, 32);
}

/**
 * `sha256(writeToken)`, hex-encoded — what actually gets sent to the
 * relay (as `initialWriteTokenHash`/`newWriteTokenHash`) or compared
 * against (the relay hashes a presented raw token the same way). Must
 * match the server's own `hashWriteToken` byte-for-byte — see
 * internal/storage/logstore/dynamodb/log_store.go.
 */
export function hashWriteToken(writeToken: Uint8Array): string {
  return bytesToHex(sha256(writeToken));
}

/**
 * The exact byte sequence an authority signature must cover for a rotate
 * call — must match the relay's own `logstore.RotateMessage` byte-for-byte.
 */
export function deriveRotateMessage(syncId: string, entryId: string, newWriteTokenHash: string): Uint8Array {
  return new TextEncoder().encode(`circle-relay/rotate/v1\x00${syncId}\x00${entryId}\x00${newWriteTokenHash}`);
}

/**
 * The exact byte sequence an authority signature must cover to obtain a
 * cover-photo upload URL — must match the relay's own
 * `logstore.CoverPhotoUploadMessage` byte-for-byte.
 */
export function deriveCoverPhotoUploadMessage(syncId: string): Uint8Array {
  return new TextEncoder().encode(`circle-relay/cover-photo-upload/v1\x00${syncId}`);
}

/**
 * Encrypts `plaintext` under the circle's shared secret using
 * XChaCha20-Poly1305 (AEAD — tampering makes decrypt fail, it doesn't
 * silently return corrupted data). A fresh random nonce is generated per
 * call and prepended to the returned bytes, since decrypt needs it back.
 */
export function encrypt(plaintext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = randomBytes(NONCE_LENGTH);
  const ciphertext = xchacha20poly1305(secret, nonce).encrypt(plaintext);
  return concatBytes(nonce, ciphertext);
}

/**
 * Encrypts a JSON-serializable value under the circle's shared secret —
 * the shape every relay log entry's envelope takes (see
 * server/DESIGN.md). A thin convenience over `encrypt` for structured
 * data instead of raw bytes.
 */
export function encryptJSON(value: unknown, secret: Uint8Array): Uint8Array {
  return encrypt(new TextEncoder().encode(JSON.stringify(value)), secret);
}

/**
 * Decrypts what `encrypt` produced: splits the leading nonce back off,
 * then decrypts the rest. Throws if the ciphertext was tampered with or
 * `secret` doesn't match what it was encrypted under.
 */
export function decrypt(ciphertext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = ciphertext.subarray(0, NONCE_LENGTH);
  const box = ciphertext.subarray(NONCE_LENGTH);
  return xchacha20poly1305(secret, nonce).decrypt(box);
}

/**
 * `sha256(bytes)`, hex-encoded — a generic content hash, distinct from
 * `hashWriteToken`. Binds a blob's actual bytes into a log entry's
 * already-signed payload (e.g. `photoHash`), catching a member swapping
 * another member's uploaded photo — something a shared write token can't
 * prevent on its own.
 */
export function hashBytes(bytes: Uint8Array): string {
  return bytesToHex(sha256(bytes));
}

/**
 * Signs `message` with `secretKey`, producing a 64-byte Ed25519 signature
 * that anyone holding the matching public key can verify — without ever
 * needing the secret key themselves.
 */
export function sign(message: Uint8Array, secretKey: Uint8Array): Uint8Array {
  return ed25519.sign(message, secretKey);
}

/**
 * Verifies that `signature` over `message` was produced by whoever holds
 * the secret key matching `publicKey`. Returns false on any mismatch or
 * tampering — never throws for an invalid signature.
 */
export function verify(signature: Uint8Array, message: Uint8Array, publicKey: Uint8Array): boolean {
  return ed25519.verify(signature, message, publicKey);
}

const INVITE_TAG_DOMAIN = new TextEncoder().encode('invite-tag');
const INVITE_PREVIEW_KEY_DOMAIN = new TextEncoder().encode('invite-preview');
const JOIN_REQUEST_KEY_DOMAIN = new TextEncoder().encode('join-request');
const SEALED_BOX_KEY_DOMAIN = new TextEncoder().encode('join-approval-box');
const X25519_PUBLIC_KEY_LENGTH = 32;

/**
 * Derives the relay-visible tag for an invite's mailbox row —
 * `sha256('invite-tag' || invite_code)`, hex-encoded. Both the invite's
 * creator and anyone holding the code compute this independently; same
 * domain-separated-hash pattern as `deriveCircleLogId`.
 */
export function deriveInviteTag(inviteCode: string): string {
  return bytesToHex(sha256(concatBytes(INVITE_TAG_DOMAIN, new TextEncoder().encode(inviteCode))));
}

/**
 * `HKDF(invite_code, "invite-preview")` — the symmetric key that
 * encrypts/decrypts an invite's preview row (circle name + cover
 * thumbnail). Computable by both the creator and anyone holding the code;
 * see server/INVITE_FLOW.md's "two encryption schemes" section.
 */
export function deriveInvitePreviewKey(inviteCode: string): Uint8Array {
  return hkdf(sha256, new TextEncoder().encode(inviteCode), undefined, INVITE_PREVIEW_KEY_DOMAIN, 32);
}

/**
 * `HKDF(invite_code, "join-request")` — the symmetric key that
 * encrypts/decrypts a requester's `{ephemeralPublicKey, selfReportedName}`
 * payload. Same code-derived-key scheme as `deriveInvitePreviewKey`, a
 * different purpose string so the two keys are unrelated.
 */
export function deriveJoinRequestKey(inviteCode: string): Uint8Array {
  return hkdf(sha256, new TextEncoder().encode(inviteCode), undefined, JOIN_REQUEST_KEY_DOMAIN, 32);
}

/**
 * Generates a fresh one-time X25519 keypair for a single handshake message
 * — never reused, never persisted beyond that one exchange. Used for the
 * asymmetric half of the invite flow (see `sealToPublicKey`), where a
 * per-message keypair is what lets the recipient decrypt without ever
 * needing to know the sender's identity in advance.
 */
export function generateEphemeralKeypair(): Keypair {
  return x25519.keygen();
}

/**
 * Derives the AEAD key for one sealed-box message from its ECDH shared
 * secret. Binding both public keys into the HKDF info (not just the raw
 * shared secret) is standard sealed-box practice — it ties the derived key
 * to this specific sender/recipient pairing, the same way every other
 * derived key in this file is domain-separated rather than using raw key
 * material directly.
 */
function sealedBoxKey(sharedSecret: Uint8Array, senderPublicKey: Uint8Array, recipientPublicKey: Uint8Array): Uint8Array {
  return hkdf(sha256, sharedSecret, undefined, concatBytes(SEALED_BOX_KEY_DOMAIN, senderPublicKey, recipientPublicKey), 32);
}

/**
 * Seals `plaintext` to `recipientPublicKey` (X25519) — the asymmetric half
 * of the invite flow, used only for the approval response (see
 * server/INVITE_FLOW.md's "two encryption schemes" section). Generates a
 * fresh one-time keypair for this message alone, ECDHs it against the
 * recipient, derives an AEAD key from the shared secret via
 * `sealedBoxKey`, then encrypts with the same `encrypt()` every other
 * ciphertext in this file uses. The sender's ephemeral public key is
 * prepended to the output, so the recipient can open this with nothing
 * but their own secret key — no sender identity needs to be known in
 * advance.
 */
export function sealToPublicKey(plaintext: Uint8Array, recipientPublicKey: Uint8Array): Uint8Array {
  const ephemeral = x25519.keygen();
  const shared = x25519.getSharedSecret(ephemeral.secretKey, recipientPublicKey);
  const key = sealedBoxKey(shared, ephemeral.publicKey, recipientPublicKey);
  return concatBytes(ephemeral.publicKey, encrypt(plaintext, key));
}

/**
 * Opens what `sealToPublicKey` produced, using `recipientKeypair`'s own
 * secret key — the only thing the recipient needs, since the sender's
 * ephemeral public key travels inside `sealed` itself. Throws if `sealed`
 * was tampered with or doesn't match `recipientKeypair`.
 */
export function openSealedBox(sealed: Uint8Array, recipientKeypair: Keypair): Uint8Array {
  const senderPublicKey = sealed.subarray(0, X25519_PUBLIC_KEY_LENGTH);
  const box = sealed.subarray(X25519_PUBLIC_KEY_LENGTH);
  const shared = x25519.getSharedSecret(recipientKeypair.secretKey, senderPublicKey);
  const key = sealedBoxKey(shared, senderPublicKey, x25519.getPublicKey(recipientKeypair.secretKey));
  return decrypt(box, key);
}
