import { ed25519 } from '@noble/curves/ed25519.js';
import { concatBytes, randomBytes } from '@noble/curves/utils.js';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { generateMnemonic, mnemonicToEntropy } from '@scure/bip39';
import { wordlist } from '@scure/bip39/wordlists/english.js';
import { randomUUID } from 'expo-crypto';

/** 128 bits of entropy — the standard tier, same security level as AES-128. */
const SEED_STRENGTH_BITS = 128;

const NONCE_LENGTH = 24;

/**
 * Generates a locally-unique, self-assigned ID (a native RFC4122 UUID v4).
 * One generator, used directly wherever an entity (a circle, a member, a
 * post, ...) needs an ID — no per-entity wrapper function, so adding a new
 * entity type never means adding a new method here that just forwards to
 * this one.
 *
 * For anything a *member* self-assigns to reference themselves (like a
 * post's author, or their own roster entry), it must be generated by that
 * member at the moment they need it, never derived from other members'
 * existing state — that's what lets every device replay the same event
 * and agree on the same ID with zero coordination.
 */
export function generateUUID(): string {
  return randomUUID();
}

/**
 * Generates a fresh 12-word recovery phrase (128 bits of entropy). This is
 * the device's one master seed — persisted locally (never sent anywhere,
 * never shown in the UI today) so future circles can derive their keys
 * from it without asking the user to retype it every time. A manual
 * backup/reveal path (words, QR, or otherwise) is deliberately deferred —
 * not designed yet, nothing to point to for it.
 */
export function generateSeedPhrase(): string {
  return generateMnemonic(wordlist, SEED_STRENGTH_BITS);
}

/**
 * Recovers the raw 16-byte entropy behind a seed phrase — either the one
 * just generated (to persist it) or one a user typed back in during
 * recovery. Throws if the words or checksum aren't a valid BIP39 phrase,
 * which catches most transcription mistakes immediately rather than
 * silently deriving the wrong keys.
 */
export function seedPhraseToEntropy(phrase: string): Uint8Array {
  return mnemonicToEntropy(phrase, wordlist);
}

export type Keypair = {
  publicKey: Uint8Array;
  secretKey: Uint8Array;
};

/**
 * Digits 1-9 plus A-Z minus I/L/O — drops the pairs most often misread
 * (0/O, 1/I/L) when handwritten or read aloud. Exactly 32 symbols so each
 * one maps to 5 bits of a random byte with zero modulo bias (256 / 32 = 8).
 */
const INVITE_CODE_ALPHABET = '123456789ABCDEFGHJKMNPQRSTUVWXYZ';

/**
 * Generates a circle invite code: 12 random characters from a
 * confusion-resistant alphabet, grouped for readability (`XXXX-XXXX-XXXX`).
 * 60 bits of entropy — short enough to read aloud or type by hand, unlike
 * a full UUID, while still being infeasible to guess within an invite's
 * short lifetime. The same string backs both the shareable link and the
 * QR code — there's only ever one secret here, just two presentations of it.
 */
export function generateInviteCode(): string {
  const bytes = randomBytes(12);
  const chars = Array.from(bytes, (byte) => INVITE_CODE_ALPHABET[byte % INVITE_CODE_ALPHABET.length]);
  return [chars.slice(0, 4), chars.slice(4, 8), chars.slice(8, 12)].map((group) => group.join('')).join('-');
}

/**
 * Generates a fresh Ed25519 identity keypair. Call this once per circle —
 * never reuse the same keypair across circles, or your public key becomes
 * a stable pseudonym that links your membership across otherwise-unrelated
 * groups (see the cross-circle correlation discussion).
 */
export function generateIdentity(): Keypair {
  return ed25519.keygen();
}

/**
 * Generates a fresh circle secret: 32 random bytes, unrelated to any
 * keypair. This is the symmetric secret shared with every member of one
 * circle — used to derive routing tags and encrypt/decrypt circle content.
 */
export function generateCircleSecret(): Uint8Array {
  return randomBytes(32);
}

/**
 * Encrypts `plaintext` under the circle's shared secret using
 * XChaCha20-Poly1305 (AEAD — tampering makes decrypt fail, it doesn't
 * silently return corrupted data). A fresh random nonce is generated per
 * call and prepended to the returned bytes, since decrypt needs it back.
 */
export function encrypt(plaintext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = randomBytes(NONCE_LENGTH);
  const ciphertext = xchacha20poly1305(secret, nonce).encrypt(plaintext);
  return concatBytes(nonce, ciphertext);
}

/**
 * Decrypts what `encrypt` produced: splits the leading nonce back off,
 * then decrypts the rest. Throws if the ciphertext was tampered with or
 * `secret` doesn't match what it was encrypted under.
 */
export function decrypt(ciphertext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = ciphertext.subarray(0, NONCE_LENGTH);
  const box = ciphertext.subarray(NONCE_LENGTH);
  return xchacha20poly1305(secret, nonce).decrypt(box);
}

/**
 * Signs `message` with `secretKey`, producing a 64-byte Ed25519 signature
 * that anyone holding the matching public key can verify — without ever
 * needing the secret key themselves.
 */
export function sign(message: Uint8Array, secretKey: Uint8Array): Uint8Array {
  return ed25519.sign(message, secretKey);
}

/**
 * Verifies that `signature` over `message` was produced by whoever holds
 * the secret key matching `publicKey`. Returns false on any mismatch or
 * tampering — never throws for an invalid signature.
 */
export function verify(signature: Uint8Array, message: Uint8Array, publicKey: Uint8Array): boolean {
  return ed25519.verify(signature, message, publicKey);
}
