import { normalizeBlob } from '@/lib/db/blob';
import { db } from '@/lib/db/connection';

export type Member = {
  circleId: string;
  publicKey: string;
  memberId: string;
  name: string;
  picture: Uint8Array | null;
  joinedAt: number;
};

const MEMBER_COLUMNS = `
  circle_id AS circleId, public_key AS publicKey, member_id AS memberId,
  name, picture, joined_at AS joinedAt
`;

function normalizeMember(member: Member): Member {
  return { ...member, picture: normalizeBlob(member.picture) };
}

/**
 * Inserts a new member into a circle's roster. `member.memberId` must be
 * self-generated by the joining member (via `generateMemberId()` in
 * crypto.ts) at join time and carried in their own "member joined" entry —
 * never computed here from other members' existing state. That's what
 * lets every device replay the same join event and agree on the same ID
 * with zero coordination, unlike a locally-computed sequential index.
 */
export async function insertMember(member: Member): Promise<void> {
  await db.runAsync(
    `INSERT INTO circle_members (circle_id, public_key, member_id, name, picture, joined_at)
     VALUES (?, ?, ?, ?, ?, ?)`,
    member.circleId,
    member.publicKey,
    member.memberId,
    member.name,
    member.picture,
    member.joinedAt,
  );
}

/** Looks up a member by their public key — used to verify a post's signature. */
export async function getMemberByPublicKey(circleId: string, publicKey: string): Promise<Member | null> {
  const member = await db.getFirstAsync<Member>(
    `SELECT ${MEMBER_COLUMNS} FROM circle_members WHERE circle_id = ? AND public_key = ?`,
    circleId,
    publicKey,
  );
  return member ? normalizeMember(member) : null;
}

/** Looks up a member by their compact member ID — resolves a post's key reference. */
export async function getMemberByMemberId(circleId: string, memberId: string): Promise<Member | null> {
  const member = await db.getFirstAsync<Member>(
    `SELECT ${MEMBER_COLUMNS} FROM circle_members WHERE circle_id = ? AND member_id = ?`,
    circleId,
    memberId,
  );
  return member ? normalizeMember(member) : null;
}

/** Returns every member of a circle, in join order — this is the roster. */
export async function getCircleMembers(circleId: string): Promise<Member[]> {
  const members = await db.getAllAsync<Member>(
    `SELECT ${MEMBER_COLUMNS} FROM circle_members WHERE circle_id = ? ORDER BY joined_at`,
    circleId,
  );
  return members.map(normalizeMember);
}

export async function updateMemberProfile(
  circleId: string,
  publicKey: string,
  profile: { name: string; picture: Uint8Array | null },
): Promise<void> {
  await db.runAsync(
    'UPDATE circle_members SET name = ?, picture = ? WHERE circle_id = ? AND public_key = ?',
    profile.name,
    profile.picture,
    circleId,
    publicKey,
  );
}

/** Removes a member from a circle's roster (e.g. after a kick + rotation). */
export async function deleteMember(circleId: string, publicKey: string): Promise<void> {
  await db.runAsync(
    'DELETE FROM circle_members WHERE circle_id = ? AND public_key = ?',
    circleId,
    publicKey,
  );
}
